version: '3.9'

services:
  db:
      container_name: db
      ports:
      - "5432:5432"
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: my_db
      image: postgres:14.3-alpine
      
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: test@test.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
      - "5050:80"