# Generated by Django 4.2.7 on 2023-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
